compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@apollo/experimental-nextjs-app-support@*':
    dependencies:
      next: '*'
  '@atls-ui-parts/carousel@*':
    dependencies:
      '@atls-ui-parts/dom': '*'
  '@aws-sdk/credential-provider-ini@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@aws-sdk/credential-provider-web-identity@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@aws-sdk/token-providers@*':
    dependencies:
      '@aws-sdk/client-sso-oidc': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@nestjs/microservices@*':
    dependencies:
      'amqp-connection-manager': '*'
      'amqplib': '*'
      'ioredis': '*'
      'kafkajs': '*'
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/microservices': '*'
      '@nestjs/websockets': '*'
  '@nestjs/common@*':
    dependencies:
      class-transformer: '*'
      class-validator: '*'
  '@nestjs/platform-fastify@*':
    dependencies:
      '@fastify/static': '*'
      '@fastify/view': '*'
  '@sentry/nextjs@*':
    dependencies:
      '@sentry-internal/tracing': '*'
  '@tgsnake/parser@*':
    dependencies:
      '@tgsnake/core': '*'
  framer-motion@*:
    dependencies:
      '@emotion/is-prop-valid': '*'
  knex@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
  nestjs-i18n@*:
    dependencies:
      hbs: '*'
  rehackt@*:
    dependencies:
      react: '*'
  swiper@*:
    dependencies:
      react: '*'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
