packageExtensions:
  '@apollo/client@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      react-dom: '*'
  '@apollo/link-error@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@apollo/react-ssr@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'
  '@atls-ui-parts/carousel@*':
    dependencies:
      '@atls-ui-parts/dom': '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls-ui-parts/link@*':
    peerDependencies:
      '@emotion/css': '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      next: '*'
  '@atls/next-app-with-emotion@*':
    peerDependencies:
      next: '*'
  swiper@*:
    dependencies:
      react: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs
