yarnPath: .yarn/releases/yarn.cjs

defaultSemverRangePrefix: ''

compressionLevel: mixed

enableGlobalCache: true

globalFolder: ../.yarn/berry

pnpEnableEsmLoader: true

preferReuse: true

packageExtensions:
  'framer-motion@*':
    dependencies:
      '@emotion/is-prop-valid': '*'
  '@atls-ui-parts/carousel@*':
    dependencies:
      '@atls-ui-parts/dom': '*'
  '@sentry/nextjs@*':
    dependencies:
      '@sentry-internal/tracing': '*'
  swiper@*:
    dependencies:
      react: '*'
