compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@svgr/core@*':
    dependencies:
      '@svgr/plugin-svgo': '*'
      '@svgr/plugin-jsx': '*'
      '@svgr/plugin-prettier': '*'
  '@atls/figma-theme-shadows-generator@*':
    dependencies:
      '@atls/figma-theme-generator-common': '*'
  '@atls/figma-theme-line-heights-generator@*':
    dependencies:
      '@atls/figma-theme-generator-common': '*'
  '@atls/figma-theme-fonts-generator@*':
    dependencies:
      '@atls/figma-theme-generator-common': '*'
  '@atls/figma-theme-radii-generator@*':
    dependencies:
      '@atls/figma-theme-generator-common': '*'
  '@atls/figma-theme-font-weights-generator@*':
    dependencies:
      '@atls/figma-theme-generator-common': '*'
  '@atls/figma-theme-font-sizes-generator@*':
    dependencies:
      '@atls/figma-theme-generator-common': '*'
  '@atls/figma-theme-borders-generator@*':
    dependencies:
      '@atls/figma-theme-generator-common': '*'
  '@apollo/experimental-nextjs-app-support@*':
    dependencies:
      next: '*'
  '@atls-ui-parts/carousel@*':
    dependencies:
      '@atls-ui-parts/dom': '*'
  '@aws-sdk/credential-provider-ini@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@aws-sdk/credential-provider-web-identity@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@aws-sdk/token-providers@*':
    dependencies:
      '@aws-sdk/client-sso-oidc': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@nestjs/common@*':
    dependencies:
      class-transformer: '*'
      class-validator: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/platform-fastify@*':
    dependencies:
      '@fastify/static': '*'
      '@fastify/view': '*'
  '@sentry/nextjs@*':
    dependencies:
      '@sentry-internal/tracing': '*'
  '@tgsnake/parser@*':
    dependencies:
      '@tgsnake/core': '*'
  framer-motion@*:
    dependencies:
      '@emotion/is-prop-valid': '*'
  knex@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
  nestjs-i18n@*:
    dependencies:
      hbs: '*'
  rehackt@*:
    dependencies:
      react: '*'
  swiper@*:
    dependencies:
      react: '*'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
