yarnPath: .yarn/releases/yarn.cjs

defaultSemverRangePrefix: ''

compressionLevel: mixed

enableGlobalCache: true

globalFolder: ../.yarn/berry

pnpEnableEsmLoader: true

preferReuse: true

packageExtensions:
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
  'framer-motion@*':
    dependencies:
      '@emotion/is-prop-valid': '*'
  '@atls-ui-parts/carousel@*':
    dependencies:
      '@atls-ui-parts/dom': '*'
  '@sentry/nextjs@*':
    dependencies:
      '@sentry-internal/tracing': '*'
  swiper@*:
    dependencies:
      react: '*'
  '@aws-sdk/credential-provider-ini@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@aws-sdk/credential-provider-web-identity@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@aws-sdk/token-providers@*':
    dependencies:
      '@aws-sdk/client-sso-oidc': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
