compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@atls-ui-parts/theme@*':
    dependencies:
      '@vanilla-extract/css': '*'
  '@atls-ui-parts/select@*':
    dependencies:
      '@vanilla-extract/css': '*'
  '@atls-ui-parts/link@*':
    dependencies:
      '@vanilla-extract/css': '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      '@vanilla-extract/css': '*'
  '@atls-ui-parts/input@*':
    dependencies:
      '@vanilla-extract/css': '*'
  '@atls-ui-parts/checkbox@*':
    dependencies:
      '@vanilla-extract/css': '*'
  '@atls-ui-parts/button@*':
    dependencies:
      '@vanilla-extract/css': '*'
  'rainbow-sprinkles@*':
    dependencies:
      '@vanilla-extract/dynamic': '*'
      '@vanilla-extract/css': '*'
  '@vanilla-extract/recipes@*':
    dependencies:
      '@vanilla-extract/css': '*'
  '@apollo/experimental-nextjs-app-support@*':
    dependencies:
      next: '*'
  '@atls-ui-parts/carousel@*':
    dependencies:
      '@atls-ui-parts/dom': '*'
      '@vanilla-extract/css': '*'
  '@aws-sdk/credential-provider-ini@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@aws-sdk/credential-provider-web-identity@*':
    dependencies:
      '@aws-sdk/client-sts': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@aws-sdk/token-providers@*':
    dependencies:
      '@aws-sdk/client-sso-oidc': '*'
    peerDependencies:
      '@aws-sdk/credential-provider-node': '*'
  '@nestjs/common@*':
    dependencies:
      class-transformer: '*'
      class-validator: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/platform-fastify@*':
    dependencies:
      '@fastify/static': '*'
      '@fastify/view': '*'
  '@sentry/nextjs@*':
    dependencies:
      '@sentry-internal/tracing': '*'
  '@tgsnake/parser@*':
    dependencies:
      '@tgsnake/core': '*'
  framer-motion@*:
    dependencies:
      '@emotion/is-prop-valid': '*'
  knex@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
  nestjs-i18n@*:
    dependencies:
      hbs: '*'
  rehackt@*:
    dependencies:
      react: '*'
  swiper@*:
    dependencies:
      react: '*'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
