packageExtensions:
  '@apollo/client@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      react-dom: '*'
  '@apollo/link-error@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@apollo/react-ssr@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      next: '*'
  '@atls/next-app-with-emotion@*':
    peerDependencies:
      next: '*'
  '@splidejs/react-splide@*':
    dependencies:
      react: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220304.hash-6afc8ff.cjs
