services:
  yarn:
    image: node:18
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  site:
    image: node:18
    volumes:
      - ./:/workspace
    working_dir: /workspace
    entrypoint: yarn workspace @site/app dev
    ports:
      - 3000:3000

  blog:
    image: node:18
    volumes:
      - ./:/workspace
    working_dir: /workspace
    entrypoint: yarn workspace @blog/app dev
    ports:
      - 3000:3000

  prices:
    image: node:18
    volumes:
      - ./:/workspace
    working_dir: /workspace
    entrypoint: yarn workspace @prices/service-entrypoint dev
    env_file:
      - ./.env
