volumes:
  yarn:
  pgdata:

services:
  yarn:
    image: node:22
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - yarn:/.yarn/berry
    entrypoint: yarn

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

  booking-telegram-bot:
    image: node:22
    entrypoint: yarn workspace @booking-telegram-bot/service-entrypoint dev
    ports:
      - '3000'
    volumes:
      - ./:/workspace
      - yarn:/.yarn/berry
    working_dir: /workspace
    environment:
      DB_HOST: 'db'

  operator-bot:
    image: node:22
    volumes:
      - ./:/workspace
      - yarn:/.yarn/berry
    working_dir: /workspace
    entrypoint: yarn workspace @operator-bot/service-entrypoint dev
    ports:
      - '3000'
