name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  run:
    name: Release
    uses: atls/shared/.github/workflows/pack-image.yaml@master
    permissions: write-all
    with:
      registryURL: cr.yandex
      registryUser: json_key
      imageNamePrefix: shdvor-
    secrets:
      registryKey: ${{ secrets.YCR_KEYFILE }}
      project: ${{ secrets.YCR_PROJECT_ID }}
