name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  run:
    if: github.event.pull_request.merged == true
    name: Release
    uses: atls/shared/.github/workflows/pack-image.yaml@master
    permissions: write-all
    with:
      registryURL: 'cr.yandex'
      registryUser: 'json_key'
      imageNamePrefix: 'shdvor-'
      nodeVersion: '19'
    secrets:
      registryKey: ${{ secrets.YCR_KEYFILE }}
      project: ${{ secrets.YCR_PROJECT_ID }}
